# Triggers the workflow on push events
on: [push]

name: Slither Analysis

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  slither-analysis:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'

      - name: 'Install the Node.js dependencies'
        run: 'yarn'

      - name: 'Slither Analysis'
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          sarif: ./results.sarif
          fail-on: none
          slither-args:
            --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/

      - name: 'Add slither summary'
        run: |
          echo "## Slither Analysis Result" >> $GITHUB_STEP_SUMMARY
          output="${{ steps.slither.outputs.stdout }}"
          processed_output=$(echo "$output" | sed 's/\`/"/g')
          echo "$process_output" >> $GITHUB_STEP_SUMMARY

      # Upload SARIF to security tab
      # private repo - advanced security
      # public repo - no need to activate advanced security to enable security tab
      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{ steps.slither.outputs.sarif }}
